### ISSUE TITLE
Adds Unnecessary Semicolons

### ISSUE THREAD

**Issue by Kurry** [square/spacecommander#10]
The formatter adds unneccessary semicolons to constructor arguments when they span multiple lines.

Steps to reproduce:
1. I added spacecommander in as a git submodule in my repo.
2. I added a pre install hook in my Podfile, and then looked at the diff.

```ruby
pre_install do |installer|
  `./Libraries/spacecommander/format-objc-files-in-repo.sh`
end
```
![screen shot 2015-06-27 at 7 33 08 pm](https://cloud.githubusercontent.com/assets/857247/8394386/689a51b8-1d03-11e5-9a21-7439e782c4f3.png)

![screen shot 2015-06-27 at 7 37 08 pm](https://cloud.githubusercontent.com/assets/857247/8394396/ef662474-1d03-11e5-9d6a-ea5235dea568.png)

**Comment by alanf** [comment]
Thanks for the report. Addressed in https://github.com/square/spacecommander/pull/11
