### ISSUE TITLE
Seemingly incorrect space in method signature.

### ISSUE THREAD

**Issue by alloy** [square/spacecommander#14]
Consider the following method signature:

```objc
+ (void)swapImplementationOf:(SEL)old with:(SEL)new
{
    // ...
}
```

For some reason the use of the word `new` triggers a space being inserted before it:

```diff
-+ (void)swapImplementationOf:(SEL)old with:(SEL)new
++ (void)swapImplementationOf:(SEL)old with:(SEL) new
```

This doesn’t seem to be a configurable option, so it appears to be a bug. I did a quick search through the codebase but couldn’t find anything related to `new`, so at least filing a ticket for now.

I’m working around it for now by renaming the parameter.

**Comment by alanf** [comment]
Ah, `clang-format` interprets `new` as the C++ keyword and adds a space between it and the parent (I don't know of a `clang-format` rule to disable this behavior either). 

You may wish to file a bug with LLVM about this: https://llvm.org/bugs/enter_bug.cgi

Thanks for the report!

**Comment by alloy** [comment]
Gotcha, thanks!

**Comment by alanf** [comment]
Another example of this we encountered:

`+ (instancetype) new NS_UNAVAILABLE;`
