### ISSUE TITLE
#if __has_include gets extra spaces

### ISSUE THREAD

**Issue by orta** [square/spacecommander#15]
`#if __has_include(<SafariServices/SafariServices.h>)` is turned into `#if __has_include(<SafariServices / SafariServices.h>)`

**Comment by alanf** [comment]
This is an issue that is part of `clang-format`, it must interpret this as a division statement.

Here are some links related to it:
https://github.com/bengardner/uncrustify/issues/378

I was able to fix this specific issue by creating a custom formatter:
https://github.com/square/spacecommander/pull/16

**Comment by orta** [comment]
Thanks @alanf - this seems like a reasonable answer to me :+1:
