### ISSUE TITLE
Run at compile-time?

### ISSUE THREAD

**Issue by JALsnipe** [square/spacecommander#25]
Is it possible to run Space Commander in Xcode, possibly as a run script phase, to identify and address potential styling issues at compile-time rather than at the point of commit?

**Comment by alanf** [comment]
I believe so, but you might have to make one modification. In `lib/common.sh`, the function `objc_files_to_format()` uses the argument `--cached` which means only files that are staged for commit will be tested for formatting issues. Make sure you remove that. 

Then, create a new "Run Script" phase and have it run `format-objc-hook`. I haven't tried this myself, but all the precommit hook does is run the `format-objc-hook` script.

**Comment by alanf** [comment]
Please reopen if you would still like to have this as a feature of Space Commander
