### ISSUE TITLE
Not work quite right when format the Objective-C block

### ISSUE THREAD

**Issue by BillZong** [square/spacecommander#30]
I've got my block formatted like this
```
[deviceManager syncDatasByIndexes:indexes finish:^{
[self doSomething]; // not formatted
}];
```
or this way:
```
[deviceManager syncDatasByIndexes:indexes
[deviceManager syncDatasByIndexes
                           finish:^{
  [self doSomething]; // not formatted
                           }];
```

Should I change the .clang-format "Language" value?
Or this feature hasn't supported yet?

**Comment by alanf** [comment]
Hi @BillZong,

I see:

```
    [deviceManager syncDatasByIndexes:indexes finish:^{
    [self doSomething]; // not formatted
    }];
```
gets formatted as:

```
    [deviceManager syncDatasByIndexes:indexes finish:^{
        [self doSomething]; // not formatted
    }];
```


can you please tell me what your input and expected output are? I'm not sure which output you would like to see.

**Comment by BillZong** [comment]
The second type of output.

**Comment by alanf** [comment]
Hi @BillZong 

I'm not 100% clear on what the issue is.

Can you comment on the diff here please?
https://github.com/square/spacecommander/compare/alanf/30?expand=1

**Comment by alanf** [comment]
Thank you for the bug report. Please see https://github.com/square/spacecommander/pull/32
