### ISSUE TITLE
clang-format 3.8 and block indentation

### ISSUE THREAD

**Issue by ksuther** [square/spacecommander#33]
A follow-up from #30 and #32. clang-format 3.7 and 3.8 have some pretty significant differences in how they do block formatting. The changes appear to be by design, but I disagree pretty strongly with the design (see also [this clang Bugzilla bug](https://llvm.org/bugs/show_bug.cgi?id=23585)). I've attached two files showing the difference between 3.7 and 3.8. 3.8 is extremely aggressive about block indentation, regardless of settings.

[format-test-3.8.txt](https://github.com/square/spacecommander/files/116002/format-test-3.8.txt)
[format-test-3.7.txt](https://github.com/square/spacecommander/files/116001/format-test-3.7.txt)

I made a custom build of clang-format that reverts or adds options for the behaviors that cause this change in block formatting behavior (my clang fork at https://github.com/ksuther/clang/tree/clang-format-customization and my spacecommander fork at https://github.com/ksuther/spacecommander/commit/af9708b32bcc36ebc99a4e8e5b569ba2a0dcba20).

For anyone wondering "upgrade at all?" 3.7 has a number of bugs that have been fixed. The big one is that formatting inside blocks was broken in 3.7, and fixed in 3.8 (I believe this is what #30 is about). Some small ones that I've noticed in my own code have to do with Obj-C literals, handling casting inside Obj-C literals, and general handling of parentheses in Obj-C.

**Comment by alanf** [comment]
I agree that your `clang-format` build produces much better block formatting results.

I have one more favor to ask: can you try to get your changes into clang-format upstream @ksuther? I'd want to try to keep up with `clang` development and avoid diverging for too long.

**Comment by ksuther** [comment]
It seems like some of these formatting choices were made deliberately, but I'll propose them as formatting options and see what the maintainer thinks.

**Comment by alanf** [comment]
Thank you @ksuther

**Comment by ksuther** [comment]
These changes have been submitted as a patch to clang-format in http://reviews.llvm.org/D17700.

**Comment by alanf** [comment]
thanks for submitting that @ksuther !

**Comment by segiddins** [comment]
@ksuther do you know if that patch ever went anywhere?

**Comment by ksuther** [comment]
Unfortunately not. My last set of clang-format patches were generally ignored.

**Comment by segiddins** [comment]
I think they're actually handled by https://reviews.llvm.org/D70926 now, when I add the test cases from your diff, they pass with that new setting set to `false`.
