### ISSUE TITLE
Generics in category break indentation

### ISSUE THREAD

**Issue by msanders** [square/spacecommander#41]
Currently this:

```
@interface NSDictionary<__covariant KeyType, __covariant ObjectType> (INSScrub)

@property (readonly, copy) NSDictionary<KeyType, ObjectType> *ins_scrubbed;

@end
```

Becomes this:

```
@interface NSDictionary <__covariant KeyType, __covariant ObjectType>
(INSScrub)

    @property(readonly, copy) NSDictionary<KeyType, ObjectType> *ins_scrubbed;

@end
```

Tried removing break penalties from the clang-format config but it seems to be unrelated. When I remove the type signature from the interface it works as expected.

**Comment by alanf** [comment]
Thanks for pointing this out! It looks like something that would be easy to fix with a script which runs after the fact.
