### ISSUE TITLE
Ignoring Directories

### ISSUE THREAD

**Issue by addoshi** [square/spacecommander#49]
Similar to this issue https://github.com/square/spacecommander/issues/5. 

I have some directories in my project file that contain machine generated objective-c files and would want space commander to ignore those directories. Rather than listing all other directories in `.formatting-directory`, I'd like to be able to have an ignore list in say a `.formatting-directory-ignore` file.

I made a quick attempt at the script here:
https://github.com/square/spacecommander/compare/master...addoshi:master

Let me know if this is something worth making a PR for. Thanks! :)

**Comment by alanf** [comment]
Thanks @addoshi ! I would be interested in this changeset. The only thing missing that I see is a description in the `README.md` Configuration section. Also, please have a look at https://github.com/square/spacecommander/blob/master/Contributing.md if you don't mind. Cheers!

**Comment by addoshi** [comment]
Thanks! Here's the PR: https://github.com/square/spacecommander/pull/51

(Also, I've signed the CLA.)
