### ISSUE TITLE
Can't detects new files

### ISSUE THREAD

**Issue by DeveloperPans** [square/spacecommander#52]
### Step

* Create a new file XXX.{h,m}
* `git add`
* `format-objc-files-in-repo.sh` 

Spacecommander not detect the new files.

**Comment by DeveloperPans** [comment]
`format-objc-files.sh -s` can resolve my problem. Should `format-objc-files-in-repo.sh` too?

**Comment by alanf** [comment]
Hi @DeveloperPans 

`format-objc-files-in-repo.sh`'s expected use case is for converting an entire repo's formatting, and if the git precommit hook is setup, then it's not needed after its initial run. 

`format-objc-files.sh ` expected use case is for formatting files that have changed only.

The former is looks for files that have been checked in, and although it could go either way, ignoring staged files still fits with the use cases described above.

**Comment by DeveloperPans** [comment]
got it. thanks @alanf !
